---
lessonName: Working with REST APIsss
lessonID: 19
category: introductory
topologyType: custom
lessondiagram: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-19/lessondiagram.png

utilities:
- name: linux1
  image: antidotelabs/utility
  sshuser: antidote
  sshpassword: antidotepassword

devices:
- name: vqfx1
  image: antidotelabs/vqfxspeedy:snap1
  sshuser: root
  sshpassword: VR-netlab9
  ports: [8080]

connections:
- a: vqfx1
  b: linux1
  subnet: 10.1.0.0/24

stages:
  1:
    description: Your First API Callll
    labguide: https://raw.githubusercontent.com/nre-learning/antidote/master/lessons/lesson-19/stage1/guide.md
    configs:
      vqfx1: stage1/configs/vqfx1.txt

